version: "3.9"

services:
  api:
    build: .
    container_name: tiktok_api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3000
      RATE_LIMIT_REQUESTS_PER_MINUTE: ${RATE_LIMIT_REQUESTS_PER_MINUTE:-60}
      RATE_LIMIT_REQUESTS_PER_HOUR: ${RATE_LIMIT_REQUESTS_PER_HOUR:-1000}
      CACHE_TTL: ${CACHE_TTL:-120}
      CACHE_MAX_ENTRIES: ${CACHE_MAX_ENTRIES:-100}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
